name: Generate screenshot

on:
  workflow_dispatch:

jobs:
  generate:
    name: Generate screenshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i --global turbo
      - run: turbo prune --scope=scripts
      - run: |
          cd out
          npm ci
          cd scripts
          npm run generate-screenshot
          mv screenshot.png ../../landing/public
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: landing/public/screenshot.png
          branch: screenshot-update
          delete-branch: true
          title: Screenshot update
          body: |
            > **Note**
            > This is an automated PR with an updated screenshot of the app to sync landing page with latest changes in the UI
